# Generated by Django 5.0.3 on 2024-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_number', models.IntegerField()),
                ('voivodeship', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('detection_date', models.DateTimeField()),
                ('pig_count', models.IntegerField()),
            ],
        ),
    ]
