# Generated by Django 5.0.3 on 2024-03-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracer_app', '0002_asfincident_breedingfarm_epidemiologicalreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asfincident',
            name='medical_resources',
            field=models.ManyToManyField(to='Tracer_app.medicalresource'),
        ),
    ]
