# Generated by Django 5.0.3 on 2024-03-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracer_app', '0003_asfincident_medical_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asfincident',
            name='medical_resources',
            field=models.ManyToManyField(related_name='asf_incidents_medical_resources', to='Tracer_app.medicalresource'),
        ),
    ]
