# Generated by Django 5.0.3 on 2024-03-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracer_app', '0007_remove_asfincident_veterinary_inspections'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemiologicalreport',
            name='asf_incidents',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Tracer_app.asfincident'),
        ),
    ]
