# Generated by Django 5.0.3 on 2024-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracer_app', '0009_asfincident_quarantines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedingfarm',
            name='asf_incidents',
            field=models.ManyToManyField(blank=True, related_name='breeding_farms', to='Tracer_app.asfincident'),
        ),
        migrations.AddField(
            model_name='medicalresource',
            name='asf_incidents',
            field=models.ManyToManyField(blank=True, related_name='medical_resources', to='Tracer_app.asfincident'),
        ),
    ]
