# Generated by Django 5.0.3 on 2024-04-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracer_app', '0010_breedingfarm_asf_incidents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asfincident',
            name='quarantines',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracer_app.quarantine'),
        ),
        migrations.AlterField(
            model_name='asfincident',
            name='veterinary_inspections',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracer_app.veterinaryinspection'),
        ),
    ]
